### PR TITLE
allow specifying a pre-computed X-Amz-Content-Sha256 value

### PR DESCRIPTION
**Pull request by jhford**
We're looking to use this library in a distributed environment where our server generates a list of generic http requests (e.g. method, url and headers) which get passed to a remote machine which does the actual uploading.  Our remote machine shouldn't have any aws secrets, so we need to generate the list of all these http request's metadata on the server.  Because the server will never have access to the actual content, we need to compute the value of the sha256 for the request body, send that to the server and sign based on that value.

This quick patch allows us to do that by skipping the hashing of the body.  It would also make it easier to use this library to do streaming uploads of things to s3 since it would allow you to use the streams api to compute the sha256 hash, do the signing, then use streams to write to the aws request.

### CODE REVIEW

**Comment by jhford** [comment]
@jonasfj fyi/

**Comment by mhart** [comment]
This was proposed a while back in #20 – although I think I like this approach a little better as it doesn't require another option/setting.

Can you add a test or two for this – maybe just to show that the header is left alone, even if the body differs (or is empty or whatever)

**Comment by mhart** [comment]
Ok, I reused the tests that @alirussell wrote in #42 – and then modified them to use the `X-Amz-Content-Sha256` header instead of adding a new option.

Thanks for contributing this! I released it in v1.6.0

**Comment by mhart** [comment]
(added your commit in as https://github.com/mhart/aws4/commit/8cd3d2ade8dd3c0ab6a975be6426f3aaa78bec60 btw – thanks again)

**Comment by jhford** [comment]
no worries!  thanks for merging so quickly

**Pull request closed without merging**
