### PR TITLE
Feature/fiveminute timeout

### PR DESCRIPTION
**Pull request by yousefcodes**
Issue #24 : I'm using this project to authorize requests to an API Gateway service we have. There is an issue where the X-Amz-Date is expiring after five minutes, which is expected. But what is not expected is for the signature to not get renewed. Subsequent request past the five minute mark are continued to be signed with the expired date, resulting in Signature Expired errors from the service.   I've added a line to evaluate the date and issue a new date if needed.

### CODE REVIEW

**Comment by mhart** [comment]
As commented here: https://github.com/mhart/aws4/issues/24#issuecomment-217983150

If you're passing in your own `X-Amz-Date` headers, then aws4 will use them as-is – this is deliberate so that you can explicitly specify the time if you want.

If you want aws4 to use the current time, then don't pass them in

**Comment by yousefcodes** [comment]
Okay, thanks.  Looking into it.

**Comment by mhart** [comment]
You can see in the example that aws4 will populate X-Amz-Date automatically for you – you don't need to pass it in (nor should you unless you're doing some testing or something): https://github.com/mhart/aws4#example

**Comment by mhart** [comment]
(perhaps you're reusing the same object each time that you're passing to aws4? Because aws4 modifies the object, this won't work – you'll need to pass a fresh object each time)

**Comment by yousefcodes** [comment]
I see.  In our case we are using STS and getting credentials and passing those through.  I'm looking into the headers to see what's there, I don't see an x-amz-date as part of them.

**Comment by yousefcodes** [comment]
We are passing a fresh object each time.

**Comment by mhart** [comment]
Well the only way that line of code can be executed (the one you've changed in the pull request) is if there's something already in `headers['X-Amz-Date']` – otherwise it gets the current time

**Comment by yousefcodes** [comment]
Here's what's interesting, on the first call I make `aws4` `prepareRequest` method does use `this.getDateTime` to set `query['X-Amz-Date']` but subsequent calls it just keeps on using `query['X-Amz-Date'] `

**Comment by yousefcodes** [comment]
Ok, taking a deeper look into what I'm passing through

**Comment by mhart** [comment]
(be sure to check you're not passing in a `Date` or `date` header too)

**Comment by mhart** [comment]
Sorry, are you using query string signing? I'm a bit confused now

**Comment by yousefcodes** [comment]
My credentials object has a AccessKeyId, SecretAccessKey, and a SessionToken.  Request has a host, path, region, and service.  And the first request falls right into this line:

`headers['X-Amz-Date'] = this.getDateTime()`

**Comment by mhart** [comment]
Sure, that's correct.

**Comment by mhart** [comment]
(you said in your last message you were checking `query['X-Amz-Date']`, not `headers['X-Amz-Date']` – that's why I asked if you were using query string signing)

**Comment by mhart** [comment]
If you can show me some code to reproduce this, it might help me track down what's going on

**Comment by yousefcodes** [comment]
I believe I've tracked it down.  There is a closure issue I'm trying to resolve. Basically aws4 is setting headers on the request object, that's ultimately modifying our config that contains canned request, then we're passing that around over and over again.

**Comment by mhart** [comment]
Ah closures, gotta love 'em.

Feel free to close this and #24 if you're happy you've tracked it down

**Comment by yousefcodes** [comment]
Yeah! Closing now! Thanks mhart.

**Comment by mhart** [comment]
No probs, glad you tracked it down 👍

**Comment by yousefcodes** [comment]
I fixed the issue in my end, but it motivated me to suggest this change, what do you think Michael?

**Comment by mhart** [comment]
Doesn't make sense to copy an object you've literally just passed in

If you're reusing the request object, that's your issue as a consumer to deal with

**Comment by mhart** [comment]
(it would also be a breaking change to the API – it would no longer work as it currently does in the example)

**Comment by yousefcodes** [comment]
Yeah, well I dealt with it in my end.  I can see the issue with breaking the API (would need to have conditions before copying the object).  But I do think that modifying the structure of an object (such as adding a headers property) should be done to a new object, not to the object that is passed in.

**Comment by mhart** [comment]
What I mean is:
```js
var opts = {/*...*/}
aws.sign(opts)
console.log(opts) // will log the original opts, not the signed opts
```
It would no longer work

**Comment by yousefcodes** [comment]
Yeah, I see what you mean. Sign, as a verb.

**Comment by yousefcodes** [comment]
You know, I agree with you now.  The consumer is specifically requesting our request to be signed, we should deal with that.  I was thinking of it differently.

**Comment by mhart** [comment]
Right – there's an argument to be made that it's confusing that it's a side-effect function as well as a returning one – my apologies for that – perhaps it could be clearer on the README or something

**Comment by yousefcodes** [comment]
I think details in the readme would be useful.  Though the fact that the method name is "sign" makes it kind of clear that the request object will be modified.  I was thinking of it more as a "getSignedRequest" where its going to return a new signed request object (without touching my input arg)

**Pull request closed without merging**
